condense_wildcard_suffixes = true
merge_imports = true
merge_derives = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
unstable_features = true
format_code_in_doc_comments = true